name: discord message
on: [push]
jobs:
  build:
    name: Discord notification 
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification 🛎️
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Hi, the project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'

