name: Discord Message
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/discord-action@master
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        args: The ${{ github.event_name }} event triggered first step.

